---
version: "2.0"

services:
  web:
    image: <dockerhub-username>/<docker-image-name>
    env:
      - WHICHNET=test
      - LIQUIDATOR_ADDRESS="<liquidator_Account_address>"
      - LIQUIDATOR_PRIVATE_KEY="<liquidator_Account_private_key>"
      - ROLLOVER_ADDRESS="<rollover_Account_address>"
      - ROLLOVER_PRIVATE_KEY= "<rollover_Account_private_key>"
      - ARBITRAGE_ADDRESS="<arbitrage_Account_address>"
      - ARBITRAGE_PRIVATE_KEY="<arbitrage_Account_private_key>"
         
    expose:
      - port: 3000
        as: 80
        to:
          - global: true

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 512Mi
        storage:
          size: 512Mi
  placement:
    westcoast:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        web: 
          denom: uakt
          amount: 1000

deployment:
  web:
    westcoast:
      profile: web
      count: 1
